plot_grids:
  grids:
  - title: Detectors
    nrows: 2
    ncols: 2
    cells:
    - geometry:
        row: 0
        col: 0
        row_span: 2
        col_span: 1
      config:
        workflow_id: dummy/detector_data/area_panel_xy/1
        output_name: current
        source_names:
        - area_panel
        plot_name: image
        params:
          layout:
            combine_mode: layout
            layout_columns: 2
          plot_aspect:
            aspect_type: Square
            ratio: 1.0
            stretch_mode: Fill width
          window:
            mode: latest
            window_duration_seconds: 1.0
            aggregation: auto
          plot_scale:
            x_scale: linear
            y_scale: linear
            color_scale: log
    - geometry:
        row: 0
        col: 1
        row_span: 2
        col_span: 1
      config:
        workflow_id: dummy/detector_data/panel_0_xy/1
        output_name: current
        source_names:
        - panel_0
        plot_name: image
        params:
          layout:
            combine_mode: layout
            layout_columns: 2
          plot_aspect:
            aspect_type: Square
            ratio: 1.0
            stretch_mode: Fill width
          window:
            mode: latest
            window_duration_seconds: 1.0
            aggregation: auto
          plot_scale:
            x_scale: linear
            y_scale: linear
            color_scale: log
  - title: Monitor Timeseries
    nrows: 1
    ncols: 1
    cells: []
