streams:
  # Input streams for monitor_data service
  - kind: monitor_events
    transport: http
    url: http://localhost:8001
  - kind: monitor_counts
    transport: http
    url: http://localhost:8001
  # Input streams for fake_detectors service
  - kind: detector_events
    transport: http
    url: http://localhost:8003
  # Input streams for fake_logdata service
  - kind: log
    transport: http
    url: http://localhost:8004
  # Config streams (dashboard <-> backend)
  - kind: livedata_commands
    transport: http
    url: http://localhost:9000  # Dashboard publishes commands here
  - kind: livedata_responses
    transport: http
    url: http://localhost:8002  # Backend publishes responses here
  # Output streams for monitor_data service
  - kind: livedata_data
    transport: http
    url: http://localhost:8002
  - kind: livedata_status
    transport: http
    url: http://localhost:8002
